on:
  push:
    branches:
      - <%= @branch %>

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    steps:
      - name: openfn deploy
        uses: midigofrank/cli-deploy-action@v0.1.12
        with:
          secret_input: ${{ secrets.<%= @api_secret_name %> }}
          config_path_input: '<%= @config_path %>'
