on:
  push:
    branches:
      - <%= @branch %>

concurrency:
  group: openfn-deployment
  cancel-in-progress: true

jobs:
  deploy-to-lightning:
    runs-on: ubuntu-latest
    name: A job to deploy to Lightning
    permissions:
      contents: write
    steps:
      - name: openfn deploy
        uses: openfn/cli-deploy-action@v1.0.0
        with:
          secret_input: ${{ secrets.<%= @api_secret_name %> }}
          config_path_input: '<%= @config_path %>'
