# syntax=docker/dockerfile:1
# Find eligible builder and runner images on Docker Hub. We use Ubuntu/Debian instead of
# Alpine to avoid DNS resolution issues in production.
#
# https://hub.docker.com/r/hexpm/elixir/tags?page=1&name=ubuntu
# https://hub.docker.com/_/ubuntu?tab=tags
#
#
# This file is based on these images:
#
#   - https://hub.docker.com/r/hexpm/elixir/tags - for the build image
#   - https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-20210902-slim - for the release image
#   - https://pkgs.org/ - resource for finding needed packages
#   - Ex: hexpm/elixir:1.13.2-erlang-24.2.1-debian-bullseye-20210902-slim
#
ARG ELIXIR_VERSION=1.18.3
ARG OTP_VERSION=27.3.3
ARG DEBIAN_VERSION=bookworm-20250428
ARG NODE_VERSION=22.12.0

ARG BUILDER_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"
ARG RUNNER_IMAGE="debian:${DEBIAN_VERSION}"

FROM ${BUILDER_IMAGE} as dev
ARG NODE_VERSION

# install build and dev dependencies
RUN apt-get update -y && apt-get install -y --no-install-recommends \
  build-essential curl git inotify-tools openssl ca-certificates \
  libsodium-dev cmake

# Install Node.js from NodeSource
RUN curl -fsSL https://deb.nodesource.com/setup_${NODE_VERSION%%.*}.x | bash - && \
  apt-get install -y nodejs=${NODE_VERSION}-1nodesource1

RUN apt-get clean && rm -f /var/lib/apt/lists/*_*

# prepare build dir
WORKDIR /app

# install hex + rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# set build ENV

ARG MIX_ENV="dev"
ENV MIX_ENV=${MIX_ENV}

# Disable git hook auto-install inside Docker builds to avoid
# compiling the :git_hooks dependency failing without a full .git repo.
ENV GIT_HOOKS_AUTO_INSTALL=false

COPY mix.* ./
RUN mix deps.get --only $MIX_ENV

RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config config
COPY assets assets
RUN npm install --prefix assets
RUN mix deps.compile

COPY priv priv
COPY lib lib
RUN mix lightning.install_runtime
RUN mix lightning.install_schemas
RUN mix lightning.install_adaptor_icons

COPY bin bin


ENTRYPOINT ["/app/bin/entrypoint"]

ARG PORT
EXPOSE ${PORT}

CMD ["mix", "phx.server"]
