#!/usr/bin/env bash

# Start the program in the background
exec "$@" &
pid1=$!

# Silence warnings from here on
exec >/dev/null 2>&1

# Function to handle SIGTERM gracefully
handle_sigterm() {
  kill -TERM $pid1
}

# Trap the SIGTERM signal and call the handle_sigterm function
trap 'handle_sigterm' SIGTERM

# Read from stdin in the background and
# force kill running program when stdin closes
exec 0<&0 $(
  while read; do :; done
  kill -KILL $pid1
) &
pid2=$!

# Clean up
wait $pid1
ret=$?
kill -KILL $pid2
exit $ret
