#!/usr/bin/env bash

# Start the program in the background
exec "$@" &
pid1=$!
echo "PID of the program: $pid1"  # Print the PID of the program to the console

# Silence warnings from here on
exec >/dev/null 2>&1

# Read from stdin in the background and
# kill running program when stdin closes
exec 0<&0 $(
  while read; do :; done
  kill -KILL $pid1
) &
pid2=$!
echo "PID of the background monitor: $pid2"  # Print the PID of the background monitor to the console

# Clean up
wait $pid1
ret=$?
kill -KILL $pid2
exit $ret
